Criação de service e controller de payer
AlexandraPassos/CoinCollector pull request #11
Opened 2023-05-24 22:03 UTC by EricGarcia-Asaas

2023-05-25 12:09 UTC, Yuri-Ferrari requested changes

2023-05-25 12:09 UTC, Yuri-Ferrari commented on src/test/groovy/com/coinCollector/PayerControllerSpec.groovy
> +            true == false
A criação desse teste é feito pra gerar erro, afinal true não é igual a false.
Eu sugiro não criarem testes unitários por enquanto, é algo que vai demandar um tempo de vocês pois será necessário criar testes para todos métodos e situações possíveis. Sugiro deletar esses dois arquivos de teste.

2023-05-25 12:09 UTC, Yuri-Ferrari commented on grails-app/services/com/coinCollector/PayerService.groovy
> +    def serviceMethod() {
Esse método será usado pra qual situação? Sempre deem nomes significativos para que possamos entender para que cada coisa serve

2023-05-25 12:09 UTC, Yuri-Ferrari commented on grails-app/controllers/com/coinCollector/PayerController.groovy
> +    def index() { }
Apesar de não quebrar nada, este código também não entrega nada, um controller ou service sem métodos não faz nada, sugiro criar os métodos relacionados a criação do Payer, dessa forma estará sendo entregue uma funcionalidade.

2023-05-29 12:28 UTC, EricGarcia-Asaas commented on grails-app/controllers/com/coinCollector/PayerController.groovy
> +    def index() { }
Foi adicionado o método save, para persistência dos registros no banco de dados

2023-06-02 16:52 UTC, Yuri-Ferrari approved these changes

2023-06-02 17:23 UTC, merged