Gerando a view de payer
AlexandraPassos/CoinCollector pull request #12
Opened 2023-05-25 00:53 UTC by EricGarcia-Asaas

Gerando view de payer para visualização do CRUD

2023-05-25 12:02 UTC, Yuri-Ferrari requested changes
Coloca prints e gifs pra mostrar o funcionamento e layout da tarefa

2023-05-25 12:02 UTC, Yuri-Ferrari commented on grails-app/views/payer/create.gsp
> +                    </g:if>
```suggestion
                    <g:if test="${flash.message}">
                      <div class="message" role="status">${flash.message}</div>
                    </g:if>
```
Apliquem identação, ela ajuda na leitura e manutenção do código, existem mais pontos nesse PR que podem ser melhorados

2023-05-25 12:02 UTC, Yuri-Ferrari commented on grails-app/views/payer/show.gsp
> +                            <input class="delete" type="submit" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.del
Essas duas funcionalidades ainda não foram feitas, se esses botões forem clicados não será gerado nenhum ação, o que é um problema, deixem pra criar esses botões quando os métodos forem desenvolvidos

2023-05-25 12:02 UTC, Yuri-Ferrari commented on grails-app/views/payer/show.gsp
> +                            <input class="delete" type="submit" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.del
E um aviso, não tem nada definido no projeto sobre qual será a língua a ser usada para mensagens e front, fica a critério de vocês, mas ela precisa ser a mesma em todo o projeto, se prosseguirem com inglês tudo terá que ser em inglês

2023-06-01 19:38 UTC, AlexandraPassos commented
### Funcionalidade do registro de payer.
![registrarpagador](https://github.com/AlexandraPassos/CoinCollector/assets/130087515/00ae3e51-085a-41e5-a1a1-56535c4757a3)

2023-06-02 16:57 UTC, Yuri-Ferrari requested changes

2023-06-02 16:57 UTC, Yuri-Ferrari commented on grails-app/controllers/com/coinCollector/PayerController.groovy
> +
```suggestion
```

2023-06-02 16:57 UTC, Yuri-Ferrari commented on grails-app/controllers/com/coinCollector/PayerController.groovy
> +import com.coinCollector.Payer
Nao é utilizado

2023-06-02 16:57 UTC, Yuri-Ferrari commented on grails-app/views/payer/create.gsp
> +                <input type="text" name="cpfCnpj" placeholder="123.456.789-12" maxLength = 14 id="cpfCnpj">
```suggestion
                <input type="text" name="cpfCnpj" placeholder="123.456.789-12" maxLength=14 id="cpfCnpj">
```
Retira esses espaços nas outras ocorrências também

2023-06-02 16:57 UTC, Yuri-Ferrari commented on grails-app/views/payer/create.gsp
> +            function validatePersonType() {
Aqui não está ocorrendo nenhuma validação, esse método está apenas trocando o tipo da pessoa, troca o validate por change

2023-06-02 18:39 UTC, AlexandraPassos commented on grails-app/controllers/com/coinCollector/PayerController.groovy
Retirando import não utilizado e arrumando espaçamento.

2023-06-02 18:39 UTC, AlexandraPassos commented on grails-app/controllers/com/coinCollector/PayerController.groovy
> +
Espaçamento arrumado.

2023-06-02 18:40 UTC, AlexandraPassos commented on grails-app/controllers/com/coinCollector/PayerController.groovy
> +
Linha desnecessária removida.

2023-06-02 18:40 UTC, AlexandraPassos commented on grails-app/controllers/com/coinCollector/PayerController.groovy
> +import com.coinCollector.Payer
Import com.coinCollector.Payer não utilizado removido.

2023-06-02 18:55 UTC, AlexandraPassos commented on grails-app/views/payer/create.gsp
> +            function validatePersonType() {
Troca de validatePersonType por changePersonType realizada.

2023-06-02 18:57 UTC, AlexandraPassos commented on grails-app/views/payer/create.gsp
> +                <input type="text" name="cpfCnpj" placeholder="123.456.789-12" maxLength = 14 id="cpfCnpj">
Espaços retirados nos campos de cpfCnpj e cep.

2023-06-02 19:10 UTC, AlexandraPassos commented on grails-app/views/payer/show.gsp
> +                            <input class="delete" type="submit" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.del
Botões removidos por funcionalidades não terem sido feitas ainda.
Todos os arquivos da view foram gerados juntos automaticamente pelo comando grails generate-views Payer. É melhor apagarmos os arquivos de edit.gsp e show.gsp e criarmos novamente eles em outro PR quando formos mexer com as outras partes do CRUD?

2023-06-02 19:11 UTC, AlexandraPassos commented on grails-app/views/payer/show.gsp
> +                            <input class="delete" type="submit" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.del
Decidimos que o idioma que iremos utilizar no projeto para mensagens e front será português e estamos prosseguindo assim.

2023-06-05 15:05 UTC, Yuri-Ferrari requested changes
Coloca na descrição do PR os prints e gifs de todos os templates criados, com todos os comportamentos possíveis

2023-06-05 15:05 UTC, Yuri-Ferrari commented on grails-app/views/payer/create.gsp
> +                var cpfCnpjInputReference = document.getElementById("cpfCnpj")
```suggestion
                var cpfCnpjInputReference = document.getElementById("cpfCnpj");
```
E faltou ; em outros pontos abaixo.

2023-06-05 15:05 UTC, Yuri-Ferrari commented on grails-app/views/payer/show.gsp
> +                        <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
Esses links não apontam pra nenhum lugar, logo não precisam existir ainda

2023-06-05 15:05 UTC, Yuri-Ferrari commented on grails-app/views/payer/show.gsp
> +                    </g:form>
Na mesma linha do comentário acima, se algo não está implementado, ele não deve existir

2023-06-05 16:17 UTC, AlexandraPassos commented on grails-app/views/payer/show.gsp
> +                    </g:form>
Excluindo os arquivos de edit.gsp e show.gsp por não estarmos utilizando eles ainda na parte do create para resolver esse ponto mencionado.

2023-06-05 16:17 UTC, AlexandraPassos commented on grails-app/views/payer/show.gsp
> +                        <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
Excluindo o arquivo show.gsp para não adicionar um arquivo que não faz parte do create e não acrescenta em nada por enquanto.

2023-06-05 16:19 UTC, AlexandraPassos commented on grails-app/views/payer/create.gsp
> +                var cpfCnpjInputReference = document.getElementById("cpfCnpj")
Acrescentado todos os ; que faltavam.

2023-06-06 17:02 UTC, Yuri-Ferrari approved these changes

2023-06-06 17:02 UTC, Yuri-Ferrari commented on grails-app/views/payer/create.gsp
> +        </script>
Identação pulou um nível, tem que estar no mesmo nível do form

2023-06-06 18:31 UTC, AlexandraPassos commented on grails-app/views/payer/create.gsp
> +        </script>
Arrumado para o mesmo nível do form.

2023-06-07 13:52 UTC, Yuri-Ferrari approved these changes

2023-06-07 13:52 UTC, Yuri-Ferrari commented on grails-app/views/payer/create.gsp
> +    <g:message code="${flash.message}"/>
Se já tem no main não precisa ter aqui

2023-06-07 21:27 UTC, AlexandraPassos commented on grails-app/views/payer/create.gsp
> +    <g:message code="${flash.message}"/>
Retirado do create.gsp.

2023-06-07 21:32 UTC, merged