Adicionando tratamento de exceções
AlexandraPassos/CoinCollector pull request #14
Opened 2023-06-05 16:56 UTC by AlexandraPassos

Adicionando tratamento de exceções no save.

2023-06-06 17:19 UTC, Yuri-Ferrari requested changes
Tem arquivos que não fazem parte do escopo desse PR, sugiro colocar como PR predecessor o PR que cria view.
E também coloque prints e gifs do comportamento desenvolvido.

2023-06-09 13:15 UTC, Yuri-Ferrari approved these changes

2023-06-09 13:15 UTC, Yuri-Ferrari commented on grails-app/controllers/com/coinCollector/PayerController.groovy
> +        }
Não precisa do finally, pode manter o redirect junto com o caminho feliz

2023-06-09 18:07 UTC, AlexandraPassos commented on grails-app/controllers/com/coinCollector/PayerController.groovy
> +        }
Tirando finally e mantendo redirect junto com o caminho feliz.

2023-06-09 18:12 UTC, merged