Criação do update de payer
AlexandraPassos/CoinCollector pull request #17
Opened 2023-06-12 16:38 UTC by AlexandraPassos

2023-06-12 16:56 UTC, Yuri-Ferrari requested changes

2023-06-12 16:56 UTC, Yuri-Ferrari commented on grails-app/controllers/com/coinCollector/PayerController.groovy
> +    }
Adiciona um tratamento para caso for passado um ID inexistente

2023-06-12 16:56 UTC, Yuri-Ferrari commented on grails-app/services/com/coinCollector/PayerService.groovy
> +        Payer payer = Payer.query([id: id]).get()
Sempre valide se o objeto existe antes de alterá-lo

2023-06-12 16:56 UTC, Yuri-Ferrari commented on grails-app/views/payer/edit.gsp
> +        </script>
Esse código se repete no create, crie um arquivo .js com essa lógica e importe tanto lá quanto aqui, dessa forma o mesmo código é reaproveitado, facilitando futuras manutenções

2023-06-12 19:35 UTC, AlexandraPassos commented on grails-app/views/payer/edit.gsp
> +        </script>
Foi criado um arquivo .js com essa lógica e foi colocado tanto no create.gsp quanto no edit.gsp, reaproveitando o código changePersonType.js.

2023-06-13 17:53 UTC, Yuri-Ferrari requested changes

2023-06-13 17:53 UTC, Yuri-Ferrari commented on grails-app/controllers/com/coinCollector/PayerController.groovy
> +        if (payer == null) {
```suggestion
        if (!payer) {
```
Mesmo resultado, mas fica mais limpo, altera em outros pontos do PR também

2023-06-13 17:53 UTC, Yuri-Ferrari commented on grails-app/controllers/com/coinCollector/PayerController.groovy
> +        Map params = [id: id, payer: payer]
O ID não é usado no template, podes remover

2023-06-13 17:53 UTC, Yuri-Ferrari commented on grails-app/views/payer/edit.gsp
> +        <g:if test="${payer}">
Se o Payer não existe ele nem deveria carregar esse template.
Mova essa validação pro Controller e carregue outro template com uma mensagem de feedback pro usuário.

2023-06-13 18:06 UTC, AlexandraPassos commented on grails-app/controllers/com/coinCollector/PayerController.groovy
> +        if (payer == null) {
Alterado (payer == null) para (!payer) nos dois pontos do PR que usavam dessa forma.

2023-06-13 19:23 UTC, AlexandraPassos commented on grails-app/views/payer/edit.gsp
> +        <g:if test="${payer}">
Como conversado, a validação feita já resolve esse problema.

2023-06-14 18:59 UTC, Yuri-Ferrari approved these changes
Este PR está usando como base uma branch que não é a main, ajuste isso antes de mergear

2023-06-14 19:10 UTC, merged