Integrando API Via CEP
AlexandraPassos/CoinCollector pull request #19
Opened 2023-06-14 19:05 UTC by AlexandraPassos

Mostrando a integração da API Via CEP no formulário de payer. Preenchendo o campo de CEP com um CEP válido os campos de estado, cidade, bairro e endereço são preenchidos automaticamente, caso seja inserido um CEP inválido ou um formato inválido de CEP aparecerá um aviso na tela.

![integracaoapiviacep](https://github.com/AlexandraPassos/CoinCollector/assets/130087515/40f9b449-a1d4-4a2f-9d9c-f54142b58330)

2023-06-15 21:08 UTC, Yuri-Ferrari requested changes

2023-06-15 21:08 UTC, Yuri-Ferrari commented on grails-app/assets/javascripts/viaCep.js
> +    if (cep !== "") {
Inverte a lógica, sempre trate o erro e não o acerto e aplica earlyReturn.
Aplique esse comentário em todas as outras validações que se encaixarem nesse caso.

2023-06-19 13:26 UTC, AlexandraPassos commented on grails-app/assets/javascripts/viaCep.js
> +    if (cep !== "") {
Lógica invertida e aplicado early return em todas outras validações encaixadas nesse caso.

2023-06-19 17:29 UTC, welingtonloh commented on grails-app/assets/javascripts/viaCep.js
> +    document.getElementById('state').value="...";
```suggestion
    document.getElementById("state").value="...";
```
teste

2023-06-21 14:38 UTC, welingtonloh approved these changes

2023-06-21 14:38 UTC, merged