Criando o create de customer
AlexandraPassos/CoinCollector pull request #22
Opened 2023-06-15 14:09 UTC by AlexandraPassos

Gerando os arquivos de CustomerService, CustomerController, create.gsp e index.gsp para o create de customer. 

![Peek 15-06-2023 11-03](https://github.com/AlexandraPassos/CoinCollector/assets/130087515/b9d2a7ce-383b-4960-906d-6c227dd76d9d)

2023-06-15 21:23 UTC, Yuri-Ferrari requested changes

2023-06-15 21:23 UTC, Yuri-Ferrari commented on grails-app/controllers/com/coinCollector/CustomerController.groovy
> +        } catch (ValidationException validationException) {
Tratem as exceções genéricas, da forma como está se o banco cair por exemplo a tela irá quebrar

2023-06-15 21:23 UTC, Yuri-Ferrari commented on grails-app/services/com/coinCollector/CustomerService.groovy
> +            throw new ValidationException("Erro ao salvar um cliente", validatedCustomer.errors)
Não precisa lançar uma exceção, apenas retorne o objeto com os erros e no Controller validem se o método chamado retornou erros e ai mostrem os erros

2023-06-15 21:23 UTC, Yuri-Ferrari commented on grails-app/views/customer/index.gsp
> +                    <f:table collection="${customerList}" />
Conforme alinhado remover isto, pois não faz sentido mostrar uma lista de customer

2023-06-15 21:23 UTC, Yuri-Ferrari commented on grails-app/services/com/coinCollector/CustomerService.groovy
> +    private Customer validateCustomer(Map params) {
Faltou incluir a limpeza dos dados, removendo caracteres especiais por exemplo

2023-06-16 23:10 UTC, AlexandraPassos commented on grails-app/views/customer/index.gsp
> +                    <f:table collection="${customerList}" />
Removido nesse pr.

2023-06-21 14:36 UTC, welingtonloh commented on grails-app/controllers/com/coinCollector/CustomerController.groovy
> +        Long id = params.long("id")
Coloca dentro do try essa linha de codigo

2023-06-21 14:36 UTC, welingtonloh commented on grails-app/controllers/com/coinCollector/CustomerController.groovy
> +            if (validatedCustomer.hasErrors()) {
Aqui vale o mesmo comentário: https://github.com/AlexandraPassos/CoinCollector/pull/24#discussion_r1236990374

Bora fazer esse ajuste primeiro aqui

2023-06-21 14:36 UTC, welingtonloh commented on grails-app/services/com/coinCollector/CustomerService.groovy
> +        if (validatedCustomer.hasErrors()) {
https://github.com/AlexandraPassos/CoinCollector/pull/24#discussion_r1236990374

2023-06-21 18:47 UTC, AlexandraPassos commented on grails-app/controllers/com/coinCollector/CustomerController.groovy
> +        Long id = params.long("id")
Linha de código colocada dentro do try.

2023-06-21 18:48 UTC, AlexandraPassos commented on grails-app/controllers/com/coinCollector/CustomerController.groovy
> +            if (validatedCustomer.hasErrors()) {
Ajuste feito de acordo com o que foi passado no comentário.

2023-06-21 18:48 UTC, AlexandraPassos commented on grails-app/services/com/coinCollector/CustomerService.groovy
> +        if (validatedCustomer.hasErrors()) {
Ajuste feito de acordo com o que foi passado no comentário.

2023-06-21 20:42 UTC, welingtonloh commented on grails-app/views/customer/create.gsp
> +        <title>Registrar Novo Cliente</title>
```suggestion
        <title>Criação de conta</title>
```

2023-06-21 20:42 UTC, welingtonloh commented on grails-app/views/customer/create.gsp
> +        <h1>Registro de Novo Cliente</h1>
```suggestion
        <h1>Criação de conta</h1>
```

2023-06-21 20:42 UTC, welingtonloh commented on grails-app/services/com/coinCollector/CustomerService.groovy
> +
Remover essa linha em branco

2023-06-21 20:42 UTC, welingtonloh commented on grails-app/controllers/com/coinCollector/CustomerController.groovy
> +        }
O redirect(action: 'create') não precisa estar dentro do finally?

2023-06-21 20:42 UTC, welingtonloh commented on grails-app/controllers/com/coinCollector/CustomerController.groovy
> +            flash.message = "Cliente registrado com sucesso"
Aqui faltou o flash.type

2023-06-21 20:42 UTC, welingtonloh commented on grails-app/controllers/com/coinCollector/CustomerController.groovy
> +            Long id = params.long("id")
Aqui seria legal deixar bem separado com linhas em branco entre os blocos de codigo.
Long id = params.long("id")
customerService.save(params)

flash.message = "Cliente registrado com sucesso"
flash.type

redirect

2023-06-21 22:54 UTC, AlexandraPassos commented on grails-app/controllers/com/coinCollector/CustomerController.groovy
> +            flash.message = "Cliente registrado com sucesso"
Flash.type adicionado.

2023-06-22 13:22 UTC, AlexandraPassos commented on grails-app/controllers/com/coinCollector/CustomerController.groovy
> +        }
Como combinado anteriormente, será mantido o redirect do index no try e o redirect do create será mantido nos catchs, sem finally.

2023-06-22 13:50 UTC, welingtonloh approved these changes

2023-06-22 13:50 UTC, merged