Adicionando update para customer
AlexandraPassos/CoinCollector pull request #24
Opened 2023-06-15 21:13 UTC by EricGarcia-Asaas

Agora é possível atualizar os dados já cadastrados de um customer, usando o botão de "Editar Cliente".

2023-06-16 13:01 UTC, Yuri-Ferrari requested changes
Faltou gifs e prints do implemento na descrição do PR

2023-06-16 13:01 UTC, Yuri-Ferrari commented on grails-app/views/customer/index.gsp
Alterações nesse arquivo não fazem parte do escopo desse PR, remova essa alterações

2023-06-16 13:01 UTC, Yuri-Ferrari commented on grails-app/services/com/coinCollector/CustomerService.groovy
> +    public void update(Long id, Map params) {
Faltou validações e limpeza de dados

2023-06-16 20:40 UTC, Yuri-Ferrari requested changes

2023-06-16 20:40 UTC, Yuri-Ferrari commented on grails-app/services/com/coinCollector/CustomerService.groovy
> +        if(!EmailUtils.emailIsValid(params.email)) return
Deve ser retornado alguma mensagem de feedback pro usuário

2023-06-16 20:40 UTC, Yuri-Ferrari commented on grails-app/services/com/coinCollector/CustomerService.groovy
> +            throw new Exception("Cliente não encontrado")
Aproveita e aplica o modo atual de reportar erros, o mesmo modo que a @AlexandraPassos está fazendo no PR dela.

2023-06-21 13:29 UTC, welingtonloh commented on src/main/groovy/utils/email/EmailUtils.groovy
> +        return !(email.isEmpty()) && email.matches(/^[a-z0-9\-\.]+@+[a-z0-9]+(\.com)+(\.br)*/)
Bora deixar mais legível esse codigo:

```
public static Boolean emailIsValid(String email) {
     if (email.isEmpty()) return false
     return email.matches(/^[a-z0-9\-\.]+@+[a-z0-9]+(\.com)+(\.br)*/)
}
```

2023-06-21 13:29 UTC, welingtonloh commented on grails-app/views/customer/show.gsp
> +        <title>Registro de Cliente</title>
Aqui não deveria ser a área de Informações da conta ou perfil?

2023-06-21 13:29 UTC, welingtonloh commented on grails-app/views/customer/show.gsp
> +                        <h1>Registro de Cliente</h1>
```suggestion
                        <h1>Informações da conta</h1>
```

2023-06-21 13:29 UTC, welingtonloh commented on grails-app/controllers/com/coinCollector/CustomerController.groovy
> +        Long id = params.long("id")
Envolver o código com try catch

Para o caso de erro de sintaxe ou algum conversão que falhar, o catch capturar e mostrar uma mensagem ao usuário

2023-06-21 13:29 UTC, welingtonloh commented on grails-app/controllers/com/coinCollector/CustomerController.groovy
> +        }
Deixa uma linha em branco separando blocos de codigo

2023-06-21 13:29 UTC, welingtonloh commented on grails-app/services/com/coinCollector/CustomerService.groovy
> +            return validatedCustomer
Faz da seguinte forma:
`if (paymentPushNotificationConfig.hasErrors()) throw new ValidationException(null, paymentPushNotificationConfig.errors)`

Na controller façamos assim para capturar essas mensagens de erro:
```
 } catch (ValidationException validationException) {
            flash.message = message(error: validationException.errors.allErrors[0])
            flash.type = MessageType.ERROR
        } catch (Exception exception) {
            log.error("NomeDaController.nomeDaAction >> Erro ao atualizar conta.", exception)
            flash.message = "Erro ao atualizar conta"
            flash.type = MessageType.ERROR
        }
```

2023-06-21 13:29 UTC, welingtonloh commented on grails-app/services/com/coinCollector/CustomerService.groovy
> +        existingCustomer.cpfCnpj = FormattingParameters.removeSpecialCharacters(params.cpfCnpj)
Não é certo a gente passar um valor para o validate e na hora de salvar passar outro pro atributo, precisa ser o mesmo valor 

aqui o certo é seguir uma ordem:
Map parsedParams = parseParams(params)
Customer validatedCustomer = validateCustomer(parsedParams, existingCustomer)

Dentro do parse façam as chamadas para FormattingParameters caso precise

2023-06-21 13:29 UTC, welingtonloh commented on grails-app/services/com/coinCollector/CustomerService.groovy
> +        }
else if (!PersonType.convert(params.personType)) {
   validatedCustomer.errors.reject("", null, "Tipo de pessoa inválido")
}

2023-06-21 13:29 UTC, welingtonloh commented on grails-app/services/com/coinCollector/CustomerService.groovy
> +        } else if(!NameUtils.nameIsValid(params.name)) {
```suggestion
        } else if (!NameUtils.nameIsValid(params.name)) {
```
Valida todos os demais em relação a espaçamento tbm

2023-06-21 13:29 UTC, welingtonloh commented on grails-app/services/com/coinCollector/CustomerService.groovy
> +        return validatedCustomer
Adiciona um linha em branco antes do return

2023-06-21 13:29 UTC, welingtonloh commented on grails-app/views/customer/edit.gsp
> +        <title>Editar Cliente</title>
Alterar conta ou alteração de conta são mais adequados

2023-06-21 13:29 UTC, welingtonloh commented on grails-app/views/customer/edit.gsp
> +        <h1>Atualizar registro de Cliente</h1>
Usa o mesmo que utilizar no title

2023-06-21 13:29 UTC, welingtonloh commented on grails-app/views/customer/edit.gsp
> +                <div id="cpfCnpj-container">
```suggestion
                <div id="cpf-cnpj-container">
```
Não mistura camelCase com kebab-case

2023-06-22 02:02 UTC, welingtonloh commented on src/main/groovy/utils/personType/PersonType.groovy
> +            return personType as PersonType
Dá uma reavaliada nessa parte, creio que dê para simplificar:

```
public static PaymentStatus convert(paymentStatus) {
		try {
			return paymentStatus as PaymentStatus
		} catch(Exception e) {
			return null
		}
	}
```

2023-06-22 02:02 UTC, welingtonloh commented on grails-app/controllers/com/coinCollector/CustomerController.groovy
> +            flash.message = "Cliente atualizado com sucesso"
flash.type = MessageType.SUCCESS

2023-06-22 02:04 UTC, welingtonloh commented on grails-app/services/com/coinCollector/CustomerService.groovy
> +        customer.phoneNumber = parsedParams.phoneNumber
aqui vocês pode fazer dessa maneira aqui tbm:

```
List<String> updatableProperties = [
            "companyType", "birthDate", "email", "name", "company", "responsibleName", "phone",
            "mobilePhone", "address", "addressNumber", "complement", "province", "cityString",
            "city", "postalCode", "state", "cpfCnpj", "personType", "inscricaoEstadual", "additionalEmails",
            "site", "companyCreationDate"]

		customer.properties[updatableProperties] = params
        customer.save(flush: true)
```

2023-06-23 02:33 UTC, welingtonloh commented on grails-app/services/com/coinCollector/CustomerService.groovy
> +        if(!EmailUtils.emailIsValid(params.email)) return
Aqui o ideal era deixar o update e save bem parecidos

parseParams
validateSave

Criar objeto, atribuir parametros

2023-06-23 13:25 UTC, welingtonloh approved these changes

2023-06-23 13:25 UTC, merged