Create de payment
AlexandraPassos/CoinCollector pull request #29
Opened 2023-06-26 20:21 UTC by EricGarcia-Asaas

Foi feito a tela de cadastro para cobrança. Caso os dados sejam preenchidos corretamente sera redirecionado ao index onde aparecera uma mensagem de cobrança criada com sucesso.

![createPayment](https://github.com/AlexandraPassos/CoinCollector/assets/130088877/05c73903-1fc0-4647-8838-ce8b745db4af)

2023-06-27 12:44 UTC, welingtonloh requested changes

2023-06-27 12:44 UTC, welingtonloh commented on grails-app/i18n/messages.properties
> +ENUM.BillingType.DEPOSIT=Deposito bancario
Coloca acentuação adequada

2023-06-27 12:44 UTC, welingtonloh commented on src/main/groovy/utils/paymentStatus/PaymentStatus.groovy
> +    EXPIRATED
A tradução correta para vencido é overdue

2023-06-27 12:44 UTC, welingtonloh commented on src/main/groovy/utils/billingType/BillingType.groovy
> +    public static BillingType convert(String billingType) {
Tem uma maneira mais simples de escrever os metodos convert

public static BillingType convert(billingType) { 
try {
   return billingType as BillingType

2023-06-27 12:44 UTC, welingtonloh commented on grails-app/views/payment/create.gsp
> +
Linha sobrando

2023-06-27 12:44 UTC, welingtonloh commented on grails-app/services/com/coincollector/payment/PaymentService.groovy
> +        parsedParams.customer = Customer.findById(1)
Esse deveria ser o codigo do teu parse
Map parsedParams = params
parsedParams.customer = Customer.findById(1)
parsedParams.payerId = params.long("payerId")
parsedParams.billingType = BillingType.convert(params.billingType)
parsedParams.value = params.value ? params.value as BigDecimal : 0
parsedParams.dueDate = CustomDateUtils.fromString(params.dueDate)

Dentro do validate vc valida cada um dos valores acima, se algum tiver nulo faz o validatedPayment.errors.reject(

Depois disso faz o get em payer, se tiver nulo, tbm adiciona erro ao validatedPayment

Entenda que:
Parse - deve fazer o parseamento dos dados
Validate - deve fazer a validação dos dados

2023-06-27 13:11 UTC, welingtonloh commented on grails-app/services/com/coincollector/payment/PaymentService.groovy
> +import javax.transaction.Transactional
Valida se conseguimos usar o import grails.gorm.transactions.Transactional aqui

2023-06-28 14:41 UTC, bmorais21 commented on grails-app/i18n/messages.properties
> +ENUM.BillingType.CREDIT_CARD=Cart�o de cr�dito
os caracteres estão certos?
![image](https://github.com/AlexandraPassos/CoinCollector/assets/17169640/b5d0f8f8-2290-41ff-a3c8-3f8c6aa529c4)

2023-06-28 14:41 UTC, bmorais21 commented on grails-app/services/com/coincollector/payment/PaymentService.groovy
> +        parsedParams.payer = params.long("payer")
payer como long? então seria `payerId`?

2023-06-28 14:41 UTC, bmorais21 commented on src/main/groovy/utils/billingType/BillingType.groovy
> +    }
Faz sentido criar métodos que não estão sendo utilizados? A melhor prática é criar os métodos somente quando formos utiliza-los, para evitar criação de código morto

2023-06-28 14:41 UTC, bmorais21 commented on grails-app/services/com/coincollector/payment/PaymentService.groovy
> +        parsedParams.value = params.value ? params.value as BigDecimal : 0
Qual seria o caso de uso de uma cobrança com valor 0?

2023-06-28 14:55 UTC, EricGarcia-Asaas commented on grails-app/i18n/messages.properties
> +ENUM.BillingType.CREDIT_CARD=Cart�o de cr�dito
Não conseguimos configurar o message.properties para que aceite UTF-8.

2023-06-28 19:46 UTC, bmorais21 approved these changes

2023-06-28 19:46 UTC, bmorais21 commented on grails-app/services/com/coincollector/payment/PaymentService.groovy
> +            validatedPayment.errors.reject("", null, "Erro ao selecionar pagador")
```suggestion
            validatedPayment.errors.reject("", null, "Pagador não encontrado")
```

2023-06-29 19:43 UTC, welingtonloh commented on grails-app/i18n/messages.properties
> +ENUM.BillingType.CREDIT_CARD=Cart�o de cr�dito
@EricGarcia-Asaas move as mensages para esse arquivo aqui, ele é UTF 8

![image](https://github.com/AlexandraPassos/CoinCollector/assets/13861122/a49ef7aa-5394-4344-a122-8d44b1d25145)

2023-06-30 14:12 UTC, welingtonloh commented on grails-app/services/com/coincollector/payment/PaymentService.groovy
> +        if (!parsedParams.payer) {
@EricGarcia-Asaas faltou commitar aqueles ajustes que conversamos ontem

2023-06-30 14:12 UTC, welingtonloh commented on grails-app/i18n/messages.properties
> +ENUM.BillingType.CREDIT_CARD=Cart�o de cr�dito
Consegue mover essa msgs para o arquivo correto para mergearmos esse dai?

2023-06-30 14:16 UTC, welingtonloh approved these changes

2023-06-30 14:16 UTC, merged