Adicionando a classe abstrata BasePerson
AlexandraPassos/CoinCollector pull request #7
Opened 2023-05-18 22:48 UTC by EricGarcia-Asaas

Foi criada a classe abstrata BasePerson para comportar os atributos em comum entre Payer e Customer.

2023-05-19 16:58 UTC, Yuri-Ferrari requested changes
E faltou uma propriedade que irá armazenar a data de criação do registro.

2023-05-19 16:58 UTC, Yuri-Ferrari commented on src/main/groovy/utils/baseperson/BasePerson.groovy
> +abstract class BasePerson{
Algumas boas práticas deixam o código mais elegante, dar um espaço é uma delas
```suggestion
abstract class BasePerson {
```

2023-05-19 16:58 UTC, Yuri-Ferrari commented on src/main/groovy/utils/baseperson/BasePerson.groovy
> +    String email
```suggestion
    String name

    String email
```
Uma linha em branco entre propriedades também ajuda na leitura do código

2023-05-19 16:58 UTC, Yuri-Ferrari commented on src/main/groovy/utils/baseperson/BasePerson.groovy
> +    String houseNumber
`house` dá a entender que se tratará de uma informação específica de casa, deixando apartamento, sala, galpão, etc de fora.
Sugiro `address`, o que envolve mudar o street para `address` também para fazer sentido

2023-05-19 16:58 UTC, Yuri-Ferrari commented on src/main/groovy/utils/baseperson/BasePerson.groovy
> +    String cpfCnpj
Existem CNPJs que são CPFs válidos, como serão diferenciados esses casos?

2023-05-19 16:58 UTC, Yuri-Ferrari requested changes
E faltou uma propriedade que irá armazenar a data de criação do registro.

2023-05-19 18:52 UTC, EricGarcia-Asaas commented on src/main/groovy/utils/baseperson/BasePerson.groovy
> +    String houseNumber
Concordo com relação ao uso de `addressNumber`, mas com relação a troca de `street` para a `address` não seria generalizar? Porque o uso de `address` remete ao endereço completo, `streetAdress` não seria mais válido?

2023-05-22 16:58 UTC, Yuri-Ferrari commented on src/main/groovy/utils/basePerson/BasePerson.groovy
> +abstract class BasePerson extends BaseEntity{
```suggestion
abstract class BasePerson extends BaseEntity {
```

2023-05-22 16:59 UTC, Yuri-Ferrari commented on src/main/groovy/utils/baseperson/BasePerson.groovy
> +    String cpfCnpj
Como ficou este ponto?

2023-05-24 12:57 UTC, Yuri-Ferrari approved these changes

2023-05-24 20:11 UTC, merged